name: Deploy framcore Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'framcore/**'
      - 'mkdocs.yml'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  deploy-docs:
    uses: ./.github/workflows/template_publish_docs.yml
    permissions:
      contents: write
    with:
      package_name: 'framcore'
      source_paths: '["docs/**", "framcore/**", "mkdocs.yml", "pyproject.toml"]'
